spring:
  jackson:
    time-zone: 'GMT+8'
    date-format: 'yyyy-MM-dd HH:mm:ss'
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    database: 0
    sentinel:
      nodes:
        - 192.168.181.171:26380
        - 192.168.181.171:26381
        - 192.168.181.171:26382
      master: mymaster

