spring:
  jackson:
    time-zone: 'GMT+8'
    date-format: 'yyyy-MM-dd HH:mm:ss'
  redis:
    database: 2
    # 连接超时时间
    timeout: 180

    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    sentinel:
      nodes:
#        - 127.0.0.1:26380
        #        - 127.0.0.1:26381
        #        - 127.0.0.1:26382
        - 192.168.181.129:26380
        - 192.168.181.129:26381
        - 192.168.181.129:26382
      master: mymaster

