spring:
  redis:
    host: 127.0.0.1
    port: 6379


# session配置
server:
  servlet:
    session:
      timeout: 30m    # 默认30分钟
      cookie:
        path: /       # 指定cookie存放路径为根目录，用于实现同域名下不同项目的session共享
#        domain: altitude.xin    # 指定cookie存放域名用于实现同根域名不同二级子域名的session共享
