
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


mybatis-plus:
#  typeEnumsPackage: xin.altitude.mybatisplus.entity
  #  global-config:
  #    db-config:
  #      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  #      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
  #      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #
  #  显示SQL日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
